### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by doubley612** [ustayready/SharpHose#1]
I'm executing:
`SharpHose.exe --action SPRAY_USERS --spraypassword lolz2020 --output out.txt`

And getting:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpHose.Nozzles.LDAP.LDAPNozzle.LoadDomainContext() in C:\code\SharpHose\SharpHose\Nozzles\LDAP\LDAPNozzle.cs:line 363
   at SharpHose.Nozzles.LDAP.LDAPNozzle.PrepareNozzle() in C:\code\SharpHose\SharpHose\Nozzles\LDAP\LDAPNozzle.cs:line 289
   at SharpHose.Program.Run(CLIOptions opts) in C:\code\SharpHose\SharpHose\Program.cs:line 135
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SharpHose.Program.Main(String[] args) in C:\code\SharpHose\SharpHose\Program.cs:line 24
```
What am I missing?

**Comment by ustayready** [comment]
Per the command line help reference, Output is a directory path not a file path.
